name: add_to_calendar
description: A Flutter plugin that allows opening a native UI to add an event with custom parameters to user calendar
version: 1.2.0+1
homepage: https://github.com/jonyas/flutter_add_to_calendar

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  meta: ^1.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  test:
  mockito: ^5.0.16
  matcher: ^0.12.11
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.github.jonyas.add_to_calendar
        pluginClass: AddToCalendarPlugin
      ios:
        pluginClass: AddToCalendarPlugin
